import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Demo project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto">
        <h1 className="mt-96 text-center">Demo nextjs project</h1>
        <p className="block text-center mt-5">
          <Link href="/about">
            <a>Go to about page</a>
          </Link>
        </p>
      </main>
    </div>
  );
}
