import Head from "next/head";
import Link from "next/link";
import tw from "twin.macro";
import MainLayout from "../components/Layouts/MainLayout";

const ButtonStyle = tw.a`
px-5 py-2 text-center text-red-500 border border-red-500 rounded cursor-pointer
`;

const Home = ({ data }) => {
  console.log("render home");
  return (
    <div>
      <Head>
        <title>Demo project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto">
        <h1 className="my-20">Demo nextjs project</h1>
        <Link href="/about">
          <ButtonStyle>Go to about page</ButtonStyle>
        </Link>
        <ul className="my-20">
          {data.map((item, index) => {
            return <li key={index}>{item.email}</li>;
          })}
        </ul>
        <div className="container mx-auto">
          <div className="grid md:grid-cols-4 grid-cols-2 gap-4">
            <div className="bg-red-300 w-full h-20 inline-block"></div>
            <div className="bg-red-300 w-full h-20 inline-block"></div>
            <div className="bg-red-300 w-full h-20 inline-block"></div>
            <div className="bg-red-300 w-full h-20 inline-block"></div>
            <div className="bg-red-300 w-full h-20 inline-block"></div>
            <div className="bg-red-300 w-full h-20 inline-block"></div>
            <div className="bg-red-300 w-full h-20 inline-block"></div>
            <div className="bg-red-300 w-full h-20 inline-block"></div>
            <div className="bg-red-300 w-full h-20 inline-block"></div>
            <div className="bg-red-300 w-full h-20 inline-block"></div>
            <div className="bg-red-300 w-full h-20 inline-block"></div>
            <div className="bg-red-300 w-full h-20 inline-block"></div>
            <div className="bg-red-300 w-full h-20 inline-block"></div>
            <div className="bg-red-300 w-full h-20 inline-block"></div>
            <div className="bg-red-300 w-full h-20 inline-block"></div>
          </div>
        </div>
      </main>
    </div>
  );
};

export async function getServerSideProps() {
  const res = await fetch(`https://62fbaabfe4bcaf53518aad31.mockapi.io/email`);
  const data = await res.json();

  return { props: { data } };
}

export default Home;

Home.getLayout = (page) => {
  return <MainLayout>{page}</MainLayout>;
};
