import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect } from "react";
import MainLayout from "../components/Layout/MainLayout";
import SpinnerComponent from "../components/Loading";
import { BASE_URL, postService } from "../services/post";

export default function Home({ posts }) {
  console.log(posts);
  return (
    <>
      <Head>
        <title>Mini NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SpinnerComponent />
      <MainLayout>
        <div className="mt-10 container mx-auto">
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
            {posts.map((post) => {
              return (
                <Link key={post._id} href={`/post/${post._id}`}>
                  <a>
                    <div className="w-full h-48 relative">
                      <Image
                        loader={() => `${BASE_URL}/${post.imageUrl}`}
                        src={`${BASE_URL}/${post.imageUrl}`}
                        alt={post.title}
                        layout="fill"
                        objectFit="cover"
                        priority
                      />
                    </div>
                    <h2>{post.title}</h2>
                    <span>{post.content}</span>
                  </a>
                </Link>
              );
            })}
          </div>
        </div>
      </MainLayout>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const res = await postService.getPosts();
    const posts = res.data.posts;
    return {
      props: { posts },
    };
  } catch (error) {
    console.log(error);
    return {
      props: {},
    };
  }
}
