import Head from "next/head";

const MainLayout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Demo project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header>header</header>
        <div className="min-h-screen">{children}</div>
        <footer>footer</footer>
      </main>
    </>
  );
};

export default MainLayout;
